workflows:
  ios-workflow:
    name: ChamaKids iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "iosApp/iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build iOS Framework
        script: ./gradlew :composeApp:linkReleaseFrameworkIosArm64
      - name: Build Summary
        script: |
          echo "Framework gerado com sucesso!"
          ls -R composeApp/build/bin/iosArm64/
    artifacts:
      - composeApp/build/bin/iosArm64/releaseFramework/ComposeApp.framework
    publishing:
      email:
        recipients:
          - pedroguiamaraes147@gmail.com
