# Configurações de Memória
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Suporte Android Moderno
android.useAndroidX=true
android.enableJetifier=true
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.native.ignoreDisabledTargets=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE

# Padronização
kotlin.code.style=official
