# Configurações para KMP e Compose Multiplatform
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false

# Ativa suporte para bibliotecas modernas
android.useAndroidX=true
android.enableJetifier=true

# Layout de pastas moderno para Kotlin Multiplatform
kotlin.mpp.androidSourceSetLayoutVersion=2

# Garante compatibilidade do Compose
kotlin.code.style=official
android.disallowKotlinSourceSets=false

# Correção para compatibilidade AGP 9.0+ com Kotlin Multiplatform
android.builtInKotlin=false
android.newDsl=false
