# Configurações de Memória para Build Pesado
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false

# Suporte Android Moderno
android.useAndroidX=true
android.enableJetifier=true

# Layout de pastas Multiplatform
kotlin.mpp.androidSourceSetLayoutVersion=2

# Silenciar avisos e ignorar alvos desativados (importante para CI)
kotlin.native.ignoreDisabledTargets=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE

# Padronização de código
kotlin.code.style=official
